#INITIAL SETTINGS
models_dir: models
data_dir : data


# file name and file path
cr_stop_words_file: cr_stopwords.pkl
cr_incident_type_features_names: cr_incident_type_features_names.pkl
cr_incident_prediction_model: cr_incident_prediction_model.pkl
cr_impact_dict : {'3 - Medium':3,'2 - High':2,'1 - Major':1}
cr_subgroups_features_names: cr_subgroups_features_names.pkl
cr_incident_types_dict : {'Capacity Incident':1,'Network Incident':2,'Cloud Maintenance Incident':3}
cr_capcity_subgroup_prediction_model: cr_subgroup_incident_1.pkl
cr_network_subgroup_prediction_model: cr_subgroup_incident_2.pkl
cr_cloud_subgroup_prediction_model: cr_subgroup_incident_3.pkl
cr_dataset_file: merged_v2.csv 

similar_incident_count: 5

Other_subgroup_features_names : Other_subgroup_features_name.pkl
other_subgroup_prediction_model: 'other_subgroup_model_name.pkl'

resolution_time_lookup_file : 'average_resolution_time_hour.csv'


env_incident_prediction_model : 'env_incident_model.pkl'
env_subgroup_prediction_model: 'Subgroup_IPOP_DecisionTree_MODEL.pkl'
env_subgroups_features_names :  'env_subgroup_features_name.pkl'

login_file: login.txt



#database configuration
db_config : 
 DRIVER : '{FreeTDS}'
 SERVER : '$SQL_SERVER_URL'          
 DATABASE : '$SQL_SERVER_DATABASE'
 UID: '$SQL_SERVER_USERNAME'
 PWD : '$SQL_SERVER_PASSWORD'
 PORT : '1433'


# Recivers email
receiver_email: '$NOTIFICATION_USER_LIST'
